---
# UbuntuのVPSの初期設定用Playbook
# 以下が前提となっている
#
# sshポート:22
# sshユーザ:root
# 新規作成ユーザのssh鍵ファイルの場所: ~/.ssh/id_rsa.pub
#

- hosts: target_first
  user: root
  tasks:
  - name: apt update
    apt:
      update_cache: yes
  - name: apt upgrade
    apt:
      upgrade: yes
  - name: 作業用ユーザを作成
    user:
      name: "{{ user_name }}"
      state: present
      password: "{{ ansible_become_pass | password_hash('sha512')}}"
      groups: sudo
  - name: .sshディレクトリ作成
    file:
      path: "~{{ user_name }}/.ssh"
      state: directory
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: 0700
  - name: 公開鍵を移送
    copy:
      dest: "~{{ user_name }}/.ssh/authorized_keys"
      content: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      mode: 0600
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
  - name: "待受ポートを {{ sshd_port }} に変更"
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^Port"
      insertafter: "^#Port"
      line: "Port {{ sshd_port }}"
  - name: ufwをインストール
    become: yes
    apt:
      name:
        - ufw
  - name: ufwのデフォルトポリシーをdenyに設定
    ufw:
      state: enabled
      default: deny
  - name: ufwで必要なポートでの通信を許可
    ufw:
      rule: allow
      proto: tcp
      state: enabled
      to_port: "{{ item }}"
    with_items:
      - 2222
      - 443
      - 80
  - name: ufwでipv6無効化
    lineinfile:
      dest: /etc/default/ufw
      regexp: "^IPV6=yes"
      insertafter: "^#IPV6=yes"
      line: "IPV6=no"
  - name: パスワード認証の無効化
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      insertafter: "^#PasswordAuthentication"
      line: "PasswordAuthentication no"
  - name: 公開鍵認証の有効化
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PubkeyAuthentication"
      insertafter: "^#PubkeyAuthentication"
      line: "PubkeyAuthentication yes"
  - name: rootユーザのログイン禁止
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      insertafter: "^#PermitRootLogin"
      line: "PermitRootLogin no"
  - name: sshdリスタート
    service:
      name: ssh
      state: restarted