---
- name: ufwで必要なポートでの通信を許可
  become: yes
  ufw:
    rule: allow
    proto: tcp
    state: enabled
    to_port: "{{ item }}"
  with_items:
    - 6443
    - 2379:2380
    - 10250
    - 10251
    - 10252
    - 30000:33767
- name: ブリッジを有効化
  become: yes
  lineinfile:
    dest: /etc/ufw/sysctl.conf
    line: "{{ item }}"
  with_items:
    - 'net/bridge/bridge-nf-call-ip6tables = 1'
    - 'net/bridge/bridge-nf-call-iptables = 1'
    - 'net/bridge/bridge-nf-call-arptables = 1'
- name: 再起動
  become: yes
  reboot:
    reboot_timeout: 300
- name: 必要なツールをインストール
  become: yes
  apt:
    name:
      - ebtables
      - ethtool
- name: 再起動
  become: yes
  reboot:
    reboot_timeout: 300
